import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { gql, useQuery } from "@apollo/client";

const GET_TEST = gql`
  query hello {
    hello
    a
  }
`;

export default function Home() {
  const { loading, error, data } = useQuery(GET_TEST);
  if (loading) return;
  if (error) return;
  console.info(data);
  return (
    <>
      <Head>
        <title>타이틀</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
